/** Capture the real seeded local app. Run from repo root with node scripts/pfe/record_demo.mjs.
 * FAST=1 captures screenshots only. Default records a silent browser walkthrough.
 * No application data, API responses, or UI text is mocked or replaced.
 */
import { createRequire } from 'node:module'
import { mkdir, writeFile } from 'node:fs/promises'
import path from 'node:path'
const require = createRequire(path.resolve('frontend/package.json'))
const { chromium } = require('playwright')
const root = process.cwd()
const out = path.join(root, 'docs/pfe/screenshots/demo-2026-09-11')
const videoDir = path.join(root, 'tmp/pfe/demo-video')
await mkdir(out, { recursive: true })
await mkdir(videoDir, { recursive: true })
const fast = process.env.FAST === '1'
const browser = await chromium.launch({ headless: true })
const context = await browser.newContext({ viewport: { width: 1920, height: 1080 }, deviceScaleFactor: 1,
  ...(fast ? {} : { recordVideo: { dir: videoDir, size: { width: 1920, height: 1080 } } }) })
const page = await context.newPage()
const diagnostics = { pageErrors: [], responses: [] }
page.on('pageerror', e => diagnostics.pageErrors.push(e.message))
page.on('response', r => { if (r.status() >= 400 && r.url().includes('/api/v1/')) diagnostics.responses.push(`${r.status()} ${r.url()}`) })
const origin = 'http://acme-corp.localhost:5173'
const chapters = []
const start = Date.now()
const seconds = () => (Date.now() - start) / 1000
async function capture(name, caption, hold = 10) {
  await page.waitForTimeout(1000)
  await page.screenshot({ path: path.join(out, `${name}.png`) })
  chapters.push({ name, caption, start: seconds(), url: page.url() })
  console.log(`Captured ${name}`)
  await page.waitForTimeout(fast ? 50 : hold * 1000)
}
async function go(route, text) {
  await page.goto(`${origin}${route}`, { waitUntil: 'domcontentloaded' })
  await page.getByText(text, { exact: true }).first().waitFor({ timeout: 45000 })
  await page.waitForTimeout(800)
}
try {
  await page.goto(`${origin}/login`)
  await page.getByLabel('Email address').waitFor()
  await capture('01-login', 'Panopta. Une vigilance continue sur la qualité des données', 6)
  await page.getByLabel('Email address').fill('mounir@acme.io')
  await page.getByLabel('Password').fill('demo1234')
  await page.getByRole('button', { name: /sign in/i }).click()
  await page.getByRole('heading', { name: 'Operations' }).waitFor()
  await capture('02-operations', '01. Prioriser les incidents dans un espace de travail isolé', 14)
  await page.getByText(/orders.*null rate spiked/i).first().click()
  await page.getByText('Key signals', { exact: true }).waitFor()
  const incidentUrl = page.url()
  await capture('03-incident', '02. Incident P1. Identifier les signaux et la table affectée', 14)
  await page.getByText('AI incident analysis', { exact: true }).scrollIntoViewIfNeeded()
  await capture('04-ai-analysis', '03. Analyse IA. Des hypothèses à vérifier et des actions proposées', 16)
  await page.getByText('Recommended actions', { exact: true }).scrollIntoViewIfNeeded()
  await capture('04b-recommended-actions', 'Des recommandations concrètes pour orienter la vérification humaine', 10)
  await page.getByText('Key signals', { exact: true }).scrollIntoViewIfNeeded()
  await capture('04c-key-signals', 'Revenir aux mesures. Chaque alerte conserve ses signaux observés', 10)
  await page.getByText('Assignment', { exact: true }).scrollIntoViewIfNeeded()
  if (!fast) {
    await page.locator('select').selectOption({ label: 'Data Engineering' })
    const saveAssignment = page.getByRole('button', { name: 'Save assignment', exact: true })
    if (await saveAssignment.count()) await saveAssignment.click()
    await page.getByRole('button', { name: 'Acknowledge', exact: true }).click()
    await page.waitForTimeout(1500)
  }
  await capture('04d-assignment', 'Attribuer le suivi à Data Engineering et reconnaître l’incident', 8)
  await page.getByText('View table detail', { exact: true }).click()
  await page.getByRole('heading', { name: 'public.orders' }).waitFor({ timeout: 45000 })
  await capture('05-table-profile', '04. Profil de table. Volume, fraîcheur et historique des mesures', 14)
  await page.mouse.wheel(0, 620)
  await capture('06-table-columns', 'Lire les métriques des colonnes pour préciser le diagnostic', 12)
  await go('/tables', 'Tables')
  await capture('07-tables', 'Le catalogue relie chaque actif à sa source et à sa surveillance', 10)
  await go('/monitors', 'Monitors')
  await capture('08-monitors', '05. Moniteurs. Définir des contrôles explicites et traçables', 10)
  await page.getByRole('button', { name: /new dsl monitor/i }).click()
  await page.getByText('New typed DSL monitor', { exact: true }).waitFor()
  await capture('09-monitor-builder', 'Construire un moniteur typé avec validation et aperçu', 12)
  await page.getByRole('button', { name: 'Cancel', exact: true }).click()
  await go('/reports', 'Reports')
  await capture('10-reports', '06. Rapports. Suivre la fiabilité au-delà d’un incident isolé', 12)
  await go('/teams', 'Teams')
  await capture('11-teams', '07. Équipes. Organiser les responsabilités opérationnelles', 8)
  await page.getByText('Data Engineering', { exact: true }).first().click()
  await page.getByRole('tab', { name: 'Members' }).waitFor()
  await capture('12-team-detail', 'Les membres et leurs rôles rendent la prise en charge explicite', 8)
  await page.keyboard.press('Escape')
  await go('/settings?tab=sources', 'Data sources')
  await capture('13-sources', '08. Sources. Relier les données au dispositif de surveillance', 10)
  await page.getByRole('button', { name: /add source/i }).click()
  await page.getByText('Add data source', { exact: true }).waitFor()
  await capture('14-connectors', 'Connecteurs disponibles. Les capacités varient selon le moteur', 10)
  await page.getByRole('button', { name: 'Cancel', exact: true }).click()
  await go('/settings?tab=alerts', 'Alert routes')
  await capture('15-alerts', '09. Alertes. Acheminer les incidents selon leur sévérité', 10)
  await go('/settings?tab=notifications', 'Email notification preferences')
  await capture('16-notifications', 'Chaque utilisateur règle ses préférences de notification', 8)
  await page.goto('http://localhost:8025')
  await page.getByText(/\[Panopta\].*orders.*null rate/).first().click()
  await page.getByText('HTML', { exact: true }).waitFor()
  await capture('16b-email-delivery', 'L’alerte est réellement reçue dans la messagerie de démonstration', 10)
  await go('/ai-systems', 'Governance work queue')
  await capture('17-ai-inventory', '10. Gouvernance IA. Prototype de suivi en mode observation', 12)
  await page.locator('tbody tr').first().click()
  await page.getByText('Declared data map', { exact: true }).waitFor()
  await capture('18-ai-system', 'Relier le système IA aux usages déclarés et aux contrôles', 12)
  await page.getByText('Evidence timeline', { exact: true }).scrollIntoViewIfNeeded()
  await capture('19-ai-evidence', 'Conserver la chronologie des preuves. Aucun blocage automatique', 12)
  await page.goto('http://admin.localhost:5173/login')
  await page.getByLabel('Email').fill('admin@datawatch.io')
  await page.getByLabel('Password').fill('admin1234')
  await page.getByRole('button', { name: /sign in/i }).click()
  await page.getByText('Organizations', { exact: true }).waitFor()
  await capture('20-organizations', '11. Administration. Piloter plusieurs organisations', 10)
  await page.getByRole('link', { name: 'Dashboard', exact: true }).click()
  await page.getByRole('heading', { name: 'Admin dashboard' }).waitFor()
  await capture('21-admin-dashboard', 'Une vue transversale réservée aux administrateurs de la plateforme', 10)
  await page.getByRole('link', { name: 'Organisations', exact: true }).click()
  await page.getByText('Organizations', { exact: true }).waitFor()
  await page.locator('tbody tr').filter({ hasText: 'Acme Corp' }).getByRole('button').click()
  await page.getByRole('menuitem', { name: /view details/i }).click()
  await page.getByText('Organization info', { exact: true }).waitFor()
  await capture('22-organization-detail', 'Consulter les utilisateurs et les sources d’une organisation', 10)
  await page.goto(incidentUrl)
  await page.getByText('Key signals', { exact: true }).waitFor()
  await capture('23-closing', 'Panopta. Mesurer, détecter, expliquer et organiser l’investigation', 10)
} finally {
  const video = page.video()
  await context.close()
  const rawVideo = video ? await video.path() : null
  await browser.close()
  await writeFile(path.join(videoDir, fast ? 'capture-manifest.json' : 'recording-manifest.json'), JSON.stringify({ recordedAt: new Date().toISOString(), duration: seconds(), rawVideo, chapters, diagnostics }, null, 2))
  console.log(JSON.stringify({ rawVideo, diagnostics }))
}
